version: '3.9'

services:
  servers:
    container_name: servers
    image: fabrzy/servers
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    
  loadbalancer:
    container_name: loadbalancer
    image: fabrzy/loadbalancer
    ports:
      - "8090:8090"
    
